### ISSUE TITLE
nx_wait_ticks using too much cpu

### ISSUE THREAD

**Issue by tuliom** [libnxz/power-gzip#37]
I noticed that libnxz was consuming too much CPU and started to investigate.
I found out that `nx_wait_ticks()` has the following comment:

```
	/* Save power and let other threads use the core. top may show
	   100%, only because OS doesn't know the thread runs slowly */
```

I'm afraid this comment is confusing software and hardware threads.
A hw thread is managed by the processor while the sw thread is managed by the OS.

When a HW thread has a lower priority, it will indeed save power or help the thoughput of other threads, but it will still consume resources.
top shows only software threads.  The high CPU usage exists because that software thread is still running.

Notice that Linux does not preserve the PRI after a context switch.

Looking closer, `nxu_run_job` calls `nx_wait_ticks()`, but doesn't allow to sleep:
https://github.com/libnxz/power-gzip/blob/master/lib/gzip_vas.c#L287

This is impacting negatively on systems that have a high NX gzip engine usage.

**Comment by abalib** [comment]
Tulio, busy waiting is intentional.  Although may be optimized.  This is one of my to-do items.  "Reduce CPU busy polling".  usleep(0) takes about 60 microseconds to get in and out of the kernel. So there is no point in sleeping when the sleep time is less than 60.   It was coded such that for short sleeps, the thread busy spins --while it's spinning, reduces the hardware thread priority (but should restore the h/w thread pri when it stops spinning).

**Comment by abalib** [comment]
https://github.com/libnxz/power-gzip/blob/master/lib/gzip_vas.c#L197  lower h/w/ thread priority
https://github.com/libnxz/power-gzip/blob/master/lib/gzip_vas.c#L204 restore priority

And see this
https://github.com/libnxz/power-gzip/blob/master/lib/gzip_vas.c#L218
I agree that some optimization is called for.   Here is the problem that we're trying to solve.  For small jobs, we don't want to sleep because the job will complete in less than 60 us.  If we sleep we will cause unnecessary latency.  e.g. the job completes in 1 us but you sleep for 60 us.   For large jobs, we don't want to busy spin because wastes cpu cycles while nx-gzip is running the job.

**Comment by tuliom** [comment]
@abalib Thanks!  This is valuable information.

>  If we sleep we will cause unnecessary latency.
> ...
> For large jobs, we don't want to busy spin because wastes cpu cycles while nx-gzip is running the job.

I agree with this, but I'm afraid we still need to improve the balance.  I've just seen a scenario where a program was competing for the NX gzip engine for seconds and spent 88% of the cycles on the `nx_wait_ticks`.
It seems the current implementation in `nxu_run_job` is favouring scenarios where libnxz should not sleep.

**Comment by abalib** [comment]
You may be right.  I simplified gzip_vas.c but perhaps might have broken it.   It used to be that, it would busy spin for 600 microseconds.  Once past 600, it would start doing actual usleep().  Why 600?  Because 10% of 600us is 60 us which is one usleep(0) time.  The thinking was that if the cores are busy, usleep(0) will put the library thread behind in the run queue e.g. it's a yield.  If the cores are not busy, the thread will come of the sleep at most with 10% delay.    And finally if the job is smaller than 600 us, we will see the completion immediately.  That was the original logic.  Not sure what it does at the moment.

**Comment by tuliom** [comment]
>  I simplified gzip_vas.c but perhaps might have broken it. It used to be that, it would busy spin for 600 microseconds.

This logic is still in place and working well.

I made a [couple of adjustments](https://github.com/libnxz/power-gzip/commit/f0b210f01d077cc93549ed9035ea599651170169) recently trying to clarify the rationale around that area of the code.
I simplified the code a bit as well as [decreased the power consumption of the busy loop](https://github.com/libnxz/power-gzip/commit/14a6d14872fd1cf1388aca2fb2accc7aa197d331).

While I was able to decrease the `SLEEP_THRESHOLD` from 120000 ticks to 110000 ticks, I was not able to find a better balance across all the wait periods without increasing latency or decreasing throughput.
The major issue here is that `usleep(0)` takes 55x longer to return than the NX GZIP engine.
`nanosleep()` takes the same amount of time.
Even when the server is at full load (i.e. all HW threads submitting requests to the NX GZIP engine) it's faster to just do the busy-loop than sleeping.
I estimate that we'd need to double the amount of HW threads per NX GZIP engine in order to start sleeping without impacting latency or throughput.

With that said, I'm closing this issue.
