### ISSUE TITLE
`inflateSyncPoint` symbol misssing in libnxz

### ISSUE THREAD

**Issue by kif** [libnxz/power-gzip#77]
I tried to use `libnxz` on the power9 (debian11) together with rsync for backups and there is a symbol missing: inflateSyncPoint
which should be exposed according to:
http://refspecs.linux-foundation.org/LSB_4.0.0/LSB-Core-generic/LSB-Core-generic/libz.html

**Comment by mscastanho** [comment]
@kif could you share the command you tried when you saw the issue? I couldn't reproduce it so far.

**Comment by kif** [comment]
I re-tested and now it works ... no idea why.
What I did was:
```
LD_PRELOAD=/.../power-gzip/lib/libnxz.so.0.62.2 rsync -axvz some_folder me@other:/tmp/backup
```

**Comment by abalib** [comment]
Quick commentary.  I don't think zlib inflatesyncpoint can serve the same of libnxz.   See the paragraphs on sync_flush and full_flush here https://www.bolet.org/~pornin/deflate-flush.html.  A flush is an empty deflate block with header but no data. Basically, these are byte aligning empty blocks in the compressed stream.  The client app or (the libnxz itself) while compressing on occasion may insert a flush to byte align the tail of the interrupted compressed stream (for example, stream may be interrupted because the remaining input data to be compressed has not arrived yet).  It's not possible transmit partial bytes, for example usually in network communication. Therefore a sync flush or full may be inserted to byte align the stream.   For whatever reason, it appears that rsync wants to know if the tail of the compressed stream contains a flush block or not (when it's inflating data.)  Inflatesyncpoint() appears to be the zlib function for that purpose.   

You may be able to implement this in libnxz.  I provide this only as a rough sketch; don't know if there any corner cases in my sketch.  Examine the code starting at this point https://github.com/libnxz/power-gzip/blob/master/lib/nx_inflate.c#L1321 onwards.   When nx-gzip hardware stops inflating, it will return with a 4-bit reason code SFBT.  It also outputs SUBC (source unprocessed bits count, e.g., see the C variable partial_bits). SUBC nonzero means nx-gzip couldn't process some bits in the input because they were interrupted in the middle. It's basically advising libnxz to rewind the source stream when resuming inflate.    If SUBC is non-zero it couldn't be that the tail of the interrupt stream is byte aligned (this is my conjecture.)  So if SUBC non-zero (for the right SFTB case),  inflatesyncpoint should return 0 (stream not at a sync point.)   If SUBC is zero, then the library must examine the last 2-3 bytes of the interrupted stream looking for the SYNC_FLUSH pattern (per first link above.)  If the pattern is found then inflatesyncpoint should return non-zero.  So you would do this examination each time you end up around here https://github.com/libnxz/power-gzip/blob/master/lib/nx_inflate.c#L1321.  And you would probably invent a private state variable in this struct https://github.com/libnxz/power-gzip/blob/master/lib/nx_zlib.h#L157 which gets updated each time the code is around L1321.  When inflatesyncpoint is called it will just return that variable

**Comment by mscastanho** [comment]
@abalib thanks for the hint and the links, those were very useful!

Based on the first link, there is an optimization in the sender-receiver scenario you used that allows the sender to omit the LEN/NLEN fields of the last empty block emitted by the flush. If both agree that every packet ends on a flush, the very last bytes would always be `00 00 FF FF`. This would then save 4 bytes on the wire.

The receiver can then use `inflateSyncPoint` on the received packet (a deflate stream) to check if that rule was followed. Looks like that's also what rsync is using it for: https://github.com/WayneD/rsync/blob/78b5bc66290aa24c69966110421a005faa37a625/token.c#L562-L569

The way zlib implements this function relies on the internal inflate state, which is a completely different struct on libnxz, so I agree we will need an implementation specific to libnxz to make it work properly.

Now I'll delve into the sketch above =)
